export { default as MainPage } from '../components/MainPage/MainPage'
export { default as AboutGame } from '../components/AboutPage/AboutGame'
export { default as NavBar } from './NavBar/NavBar'
export { default as Profile } from './Profile/Profile'
export { default as Register } from './Register/Register'
export { default as UserCart } from './UserCart/UserCart'
export { default as OrderInfo } from './OrderInfo/OrderInfo'